name: Criar APK da Karen

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixando o repositório
      uses: actions/checkout@v4

    - name: Configurando o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Configurando o Java (Requisito do Android)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Instalando o Cordova e Dependências
      run: |
        npm install -g cordova
        npm install

    - name: Criando Projeto Android Nativo
      run: |
        # Inicializa a estrutura de aplicativo para a Karen
        cordova create cordova_project org.homemaranha.karen KarenAI
        cd cordova_project
        cordova platform add android
        
        # Copia os seus arquivos visuais para a pasta do aplicativo
        cp -r ../index.html ../package.json ./www/

    - name: Compilando o APK Final (Debug Mode)
      run: |
        cd cordova_project
        # Aceita os termos do SDK de forma silenciosa e compila o APK padrão
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        cordova build android --device

    - name: Subir o APK Pronto
      uses: actions/upload-artifact@v4
      with:
        name: Karen-AI-APK
        path: cordova_project/platforms/android/app/build/outputs/apk/debug/*.apk
